Changed hardcoded print of [y/N] to [yes/y/NO/n] using helper function to be consistent
cfengine/cfbs pull request #161
Opened 2023-11-07 11:35 UTC by danielskinstad

Changed hardcoded print of [y/N] to [yes/y/NO/n] using helper function to be consistent

Ticket: ENT-8980

2023-11-07 13:39 UTC, larsewi requested changes
Thank you for your contribution 🚀 

Before merging please:
 - [ ] put different unrelated changes in their own commits
 - [ ] format code with the [black](https://pypi.org/project/black/) formatter for python
 - [ ] sign your commits using `git commit -s` (see https://github.com/cfengine/core/blob/master/CONTRIBUTING.md#commit-message-example)
 - [ ] add the ticket number to the PR Title (see https://github.com/cfengine/core/blob/master/CONTRIBUTING.md#pull-request-title-and-description)

Also I would recommend not committing directly to you master branch, as it can make some things a little bit more complicated for you down the line. Instead create a new branch to work on.

To do all the fixes above I would recommend getting to know how to do an interactive rebase (see https://github.com/cfengine/core/blob/master/CONTRIBUTING.md#interactive-rebase)

Lastly, don't hesitate to bombard me with questions!

2023-11-07 13:39 UTC, larsewi commented on cfbs/prompts.py
> +            print("Invalid value entered, must be one of: %s" % "/".join(choices))
This should be on a separate commit, please see https://github.com/cfengine/core/blob/master/CONTRIBUTING.md#commits

2023-11-07 13:51 UTC, olehermanse requested changes
The change itself looks good, the commits we can improve. In addition to the things mentioned by @larsewi, it also looks like you have committed as "cfbs" - please put your name and email as author / committer when you make commits.

Furthermore, it would be better if the PR title / commit title focused on what is the impact to a user. Here is my suggestion:

```
The prompt for adding all modules now has yes/y/no/n options, like the other prompts
```

Feel free to ask me for help if you are unsure about how to edit commits :)

2023-11-08 13:13 UTC, olehermanse approved these changes
Looks great now, thanks! 🚀

2023-11-08 13:13 UTC, merged

2023-11-08 13:16 UTC, larsewi commented
Congrats 🚀