ENT-10830: Build steps no longer write duplicate entries to `def.json` where appropriate
cfengine/cfbs pull request #201
Opened 2024-07-31 15:39 UTC by jakub-nt

2024-08-02 11:51 UTC, olehermanse requested changes
Looks good, as noted in Slack, please add a sentence or two about this in `JSON.md`.

2024-08-05 18:23 UTC, larsewi approved these changes
Very nice :rocket:

2024-08-06 17:45 UTC, olehermanse requested changes
Looks good in general, just one suggestion to improve the documentation.

2024-08-06 17:45 UTC, olehermanse commented on JSON.md
> +If `def.json` is modified during a build step, the values of some of its keys are deduplicated. These keys are: `"inputs"`, `"augments"`, the `"tags"` key of each variable in the `"variables"` key, t
```suggestion
When `def.json` is modified during a `json`, `input`, `directory`, `bundles`, or `policy_files` build step, the values of some lists of strings are deduplicated, when this does not make any difference in behavior.
These cases are:

1. Policy files and augments files in the `"inputs"` and `"augments"` top level keys.
2. `"tags"` inside variables in `"variables"` and classes in `"classes"`.
3. Class expressions for each class in `"classes"`.
   These are in the subkey `"class_expressions"` when the class is defined using an object, and if the class is defined using just a list, that list is the list of class expressions implicitly.
```

2024-08-10 03:31 UTC, nickanderson requested changes
Looks pretty good to me. But the first commit description could be improved, or perhaps better squash this all into a single commit.

2024-08-14 14:54 UTC, merged