Added shell test for `cfbs clean`
cfengine/cfbs pull request #63
Opened 2021-11-01 21:43 UTC by larsewi

Ticket: None
Changelog: None
Signed-off-by: Lars Erik Wik <lars.erik.wik@northern.tech>

2021-11-02 12:26 UTC, olehermanse requested changes

2021-11-02 12:26 UTC, olehermanse commented on test/shell/009_clean.sh
> +cfbs clean
I guess you should use `--non-interactive` here :)

2021-11-02 12:26 UTC, olehermanse commented on test/shell/009_clean.sh
> +set -e
Please add this to the `all.sh` script in the same folder.

2021-11-02 15:19 UTC, craigcomstock reviewed
Agree with @olehermanse comments. Otherwise looks good.

2021-11-04 19:35 UTC, olehermanse requested changes
Please rebase this now that the other one was merged. In hindsight it probably would have been better to do 2 commits in 1 PR in this case :)

2021-11-04 22:37 UTC, olehermanse commented
> Please rebase this now that the other one was merged. In hindsight it probably would have been better to do 2 commits in 1 PR in this case :)

Never mind, I fixed the conflict in GitHub UI :) Merging.

2021-11-04 22:37 UTC, merged