Added function `pretty` for pretty printing JSON
cfengine/cfbs pull request #8
Opened 2021-07-14 14:27 UTC by larsewi

Signed-off-by: larsewi <lars.erik.wik@northern.tech>

2021-07-15 12:28 UTC, cf-bottom commented
Thanks for submitting a PR! Maybe @vpodzime can review this?

2021-07-15 14:55 UTC, olehermanse requested changes

2021-07-15 14:55 UTC, olehermanse commented on cfbs/pretty_json.py
> +    def _force_wrap(parent):
`should_wrap` or `should_force_wrap` like a question.

2021-07-15 14:55 UTC, olehermanse commented on cfbs/pretty_json.py
> +                return False
Count number of children with 2 or more elements. If count is more than 1, wrap.

2021-07-15 14:55 UTC, olehermanse commented on cfbs/pretty_json.py
> +            if indent + cursor + len(buf) <= MAX_LEN:
```suggestion
            assert "\n" not in buf
            if indent + cursor + len(buf) <= MAX_LEN:
```

2021-07-15 14:55 UTC, olehermanse commented on cfbs/pretty_json.py
> +            buf += " }"
If this is only for 1 line anyway, could you just use `json.dumps()`?

2021-07-15 14:55 UTC, olehermanse commented on cfbs/pretty_json.py
> +            buf += " }"
or map or list / dict comprehension.

2021-07-15 14:55 UTC, olehermanse commented on cfbs/pretty_json.py
> +                return buf
Unclear whether buf can be multiple lines or not. Please change to json.dumps, or add asserts and map/join.

2021-07-19 07:53 UTC, vpodzime reviewed
Looks good to me otherwise. Please change the unit test to show the structure of the expected format better. The current format makes it very hard to review.

2021-07-19 07:53 UTC, vpodzime commented on cfbs/pretty.py
> +from typing import OrderedDict
`from collections import OrderedDict`

2021-07-19 07:53 UTC, vpodzime commented on cfbs/pretty.py
> +                    count += 1
I'd prefer a bit more functional-like approach here, something like:
```
count = len([child for child in parent if isinstance(child, (tuple, list, dict) and len(child) >= 2])
return rount >= 2
```
But YMMV.

2021-07-19 07:53 UTC, vpodzime commented on cfbs/pretty.py
> +            return float.__repr__(data)
You could merge these two cases into
```
elif isinstance(data, (int, float)):
    return repr(data)
```

2021-07-19 07:53 UTC, vpodzime commented on test/test_pretty.py
> +    )
I'd prefer this multiline cases to be checked like this:
```
expected = """{
  "This": "line",
  "is": "greater",
  ...
}"""
assert(pretty(...) == expected)
```

2021-07-19 11:22 UTC, olehermanse requested changes

2021-07-19 11:22 UTC, olehermanse commented on cfbs/pretty.py
> +    data = json.loads(s, object_pairs_hook=OrderedDict)
Should be possible to call a pretty function with a dictionary. 9/10 times I want to generate some dictionary, and then prettify it before saving to file or printing to terminal.

Maybe it makes sense to copy what the json module is doing (`load()`, `loads()`, `dump()`, `dumps()`). You could have `pretty()` and `pretty_string()`.

2021-07-20 09:25 UTC, larsewi commented on cfbs/pretty.py
> +                    count += 1
@vpodzime, @olehermanse  how about ?
```Python
count = len(
    filter(
        lambda child: isinstance(child, (tuple, list, dict))
        and len(child) >= 2,
        parent,
    )
)
```

2021-07-20 13:05 UTC, olehermanse approved these changes
LGTM, just a small comment.

2021-07-20 13:06 UTC, merged